class _CountryCode {
  final String name;
  final String code;
  final String dialCode;
  final String engName;

  const _CountryCode({
    required this.name,
    required this.code,
    required this.dialCode,
    required this.engName,
  });
}

const Map<String, _CountryCode> countryCodeMap = {
  'AF': _CountryCode(
    name: 'افغانستان',
    code: 'AF',
    dialCode: '+93',
    engName: 'Afghanistan',
  ),
  'AX': _CountryCode(
    name: 'Åland',
    code: 'AX',
    dialCode: '+358',
    engName: 'Åland Islands',
  ),
  'AL': _CountryCode(
    name: 'Shqipëria',
    code: 'AL',
    dialCode: '+355',
    engName: 'Albania',
  ),
  'DZ': _CountryCode(
    name: 'الجزائر',
    code: 'DZ',
    dialCode: '+213',
    engName: 'Algeria',
  ),
  'AS': _CountryCode(
    name: 'American Samoa',
    code: 'AS',
    dialCode: '+1684',
    engName: 'American Samoa',
  ),
  'AD': _CountryCode(
    name: 'Andorra',
    code: 'AD',
    dialCode: '+376',
    engName: 'Andorra',
  ),
  'AO': _CountryCode(
    name: 'Angola',
    code: 'AO',
    dialCode: '+244',
    engName: 'Angola',
  ),
  'AI': _CountryCode(
    name: 'Anguilla',
    code: 'AI',
    dialCode: '+1264',
    engName: 'Anguilla',
  ),
  'AQ': _CountryCode(
    name: 'Antarctica',
    code: 'AQ',
    dialCode: '+672',
    engName: 'Antarctica',
  ),
  'AG': _CountryCode(
    name: 'Antigua and Barbuda',
    code: 'AG',
    dialCode: '+1268',
    engName: 'Antigua and Barbuda',
  ),
  'AR': _CountryCode(
    name: 'Argentina',
    code: 'AR',
    dialCode: '+54',
    engName: 'Argentina',
  ),
  'AM': _CountryCode(
    name: 'Հայաստան',
    code: 'AM',
    dialCode: '+374',
    engName: 'Armenia',
  ),
  'AW': _CountryCode(
    name: 'Aruba',
    code: 'AW',
    dialCode: '+297',
    engName: 'Aruba',
  ),
  'AU': _CountryCode(
    name: 'Australia',
    code: 'AU',
    dialCode: '+61',
    engName: 'Australia',
  ),
  'AT': _CountryCode(
    name: 'Österreich',
    code: 'AT',
    dialCode: '+43',
    engName: 'Austria',
  ),
  'AZ': _CountryCode(
    name: 'Azərbaycan',
    code: 'AZ',
    dialCode: '+994',
    engName: 'Azerbaijan',
  ),
  'BS': _CountryCode(
    name: 'Bahamas',
    code: 'BS',
    dialCode: '+1242',
    engName: 'Bahamas',
  ),
  'BH': _CountryCode(
    name: '‏البحرين',
    code: 'BH',
    dialCode: '+973',
    engName: 'Bahrain',
  ),
  'BD': _CountryCode(
    name: 'Bangladesh',
    code: 'BD',
    dialCode: '+880',
    engName: 'Bangladesh',
  ),
  'BB': _CountryCode(
    name: 'Barbados',
    code: 'BB',
    dialCode: '+1246',
    engName: 'Barbados',
  ),
  'BY': _CountryCode(
    name: 'Белару́сь',
    code: 'BY',
    dialCode: '+375',
    engName: 'Belarus',
  ),
  'BE': _CountryCode(
    name: 'België',
    code: 'BE',
    dialCode: '+32',
    engName: 'Belgium',
  ),
  'BZ': _CountryCode(
    name: 'Belize',
    code: 'BZ',
    dialCode: '+501',
    engName: 'Belize',
  ),
  'BJ': _CountryCode(
    name: 'Bénin',
    code: 'BJ',
    dialCode: '+229',
    engName: 'Benin',
  ),
  'BM': _CountryCode(
    name: 'Bermuda',
    code: 'BM',
    dialCode: '+1441',
    engName: 'Bermuda',
  ),
  'BT': _CountryCode(
    name: 'ʼbrug-yul',
    code: 'BT',
    dialCode: '+975',
    engName: 'Bhutan',
  ),
  'BO': _CountryCode(
    name: 'Bolivia',
    code: 'BO',
    dialCode: '+591',
    engName: 'Bolivia',
  ),
  'BA': _CountryCode(
    name: 'Bosna i Hercegovina',
    code: 'BA',
    dialCode: '+387',
    engName: 'Bosnia and Herzegovina',
  ),
  'BW': _CountryCode(
    name: 'Botswana',
    code: 'BW',
    dialCode: '+267',
    engName: 'Botswana',
  ),
  'BV': _CountryCode(
    name: 'Bouvetøya',
    code: 'BV',
    dialCode: '+47',
    engName: 'Bouvet Island',
  ),
  'BR': _CountryCode(
    name: 'Brasil',
    code: 'BR',
    dialCode: '+55',
    engName: 'Brazil',
  ),
  'IO': _CountryCode(
    name: 'British Indian Ocean Territory',
    code: 'IO',
    dialCode: '+246',
    engName: 'British Indian Ocean Territory',
  ),
  'BN': _CountryCode(
    name: 'Negara Brunei Darussalam',
    code: 'BN',
    dialCode: '+673',
    engName: 'Brunei Darussalam',
  ),
  'BG': _CountryCode(
    name: 'България',
    code: 'BG',
    dialCode: '+359',
    engName: 'Bulgaria',
  ),
  'BF': _CountryCode(
    name: 'Burkina Faso',
    code: 'BF',
    dialCode: '+226',
    engName: 'Burkina Faso',
  ),
  'BI': _CountryCode(
    name: 'Burundi',
    code: 'BI',
    dialCode: '+257',
    engName: 'Burundi',
  ),
  'KH': _CountryCode(
    name: 'Cambodia',
    code: 'KH',
    dialCode: '+855',
    engName: 'Cambodia',
  ),
  'CM': _CountryCode(
    name: 'Cameroon',
    code: 'CM',
    dialCode: '+237',
    engName: 'Cameroon',
  ),
  'CA': _CountryCode(
    name: 'Canada',
    code: 'CA',
    dialCode: '+1',
    engName: 'Canada',
  ),
  'CV': _CountryCode(
    name: 'Cabo Verde',
    code: 'CV',
    dialCode: '+238',
    engName: 'Cape Verde',
  ),
  'KY': _CountryCode(
    name: 'Cayman Islands',
    code: 'KY',
    dialCode: '+1345',
    engName: 'Cayman Islands',
  ),
  'CF': _CountryCode(
    name: 'Ködörösêse tî Bêafrîka',
    code: 'CF',
    dialCode: '+236',
    engName: 'Central African Republic',
  ),
  'TD': _CountryCode(
    name: 'Tchad',
    code: 'TD',
    dialCode: '+235',
    engName: 'Chad',
  ),
  'CL': _CountryCode(
    name: 'Chile',
    code: 'CL',
    dialCode: '+56',
    engName: 'Chile',
  ),
  'CN': _CountryCode(
    name: '中国',
    code: 'CN',
    dialCode: '+86',
    engName: 'China',
  ),
  'CX': _CountryCode(
    name: 'Christmas Island',
    code: 'CX',
    dialCode: '+61',
    engName: 'Christmas Island',
  ),
  'CC': _CountryCode(
    name: 'Cocos (Keeling) Islands',
    code: 'CC',
    dialCode: '+61',
    engName: 'Cocos (Keeling) Islands',
  ),
  'CO': _CountryCode(
    name: 'Colombia',
    code: 'CO',
    dialCode: '+57',
    engName: 'Colombia',
  ),
  'KM': _CountryCode(
    name: 'Komori',
    code: 'KM',
    dialCode: '+269',
    engName: 'Comoros',
  ),
  'CG': _CountryCode(
    name: 'République du Congo',
    code: 'CG',
    dialCode: '+242',
    engName: 'Congo',
  ),
  'CD': _CountryCode(
    name: 'République démocratique du Congo',
    code: 'CD',
    dialCode: '+243',
    engName: 'Congo, The Democratic Republic of the',
  ),
  'CK': _CountryCode(
    name: 'Cook Islands',
    code: 'CK',
    dialCode: '+682',
    engName: 'Cook Islands',
  ),
  'CR': _CountryCode(
    name: 'Costa Rica',
    code: 'CR',
    dialCode: '+506',
    engName: 'Costa Rica',
  ),
  'CI': _CountryCode(
    name: "Côte d'Ivoire",
    code: 'CI',
    dialCode: '+225',
    engName: "Côte d'Ivoire",
  ),
  'HR': _CountryCode(
    name: 'Hrvatska',
    code: 'HR',
    dialCode: '+385',
    engName: 'Croatia',
  ),
  'CU': _CountryCode(
    name: 'Cuba',
    code: 'CU',
    dialCode: '+53',
    engName: 'Cuba',
  ),
  'CY': _CountryCode(
    name: 'Κύπρος',
    code: 'CY',
    dialCode: '+357',
    engName: 'Cyprus',
  ),
  'CZ': _CountryCode(
    name: 'Česká republika',
    code: 'CZ',
    dialCode: '+420',
    engName: 'Czech Republic',
  ),
  'DK': _CountryCode(
    name: 'Danmark',
    code: 'DK',
    dialCode: '+45',
    engName: 'Denmark',
  ),
  'DJ': _CountryCode(
    name: 'Djibouti',
    code: 'DJ',
    dialCode: '+253',
    engName: 'Djibouti',
  ),
  'DM': _CountryCode(
    name: 'Dominica',
    code: 'DM',
    dialCode: '+1767',
    engName: 'Dominica',
  ),
  'DO': _CountryCode(
    name: 'República Dominicana',
    code: 'DO',
    dialCode: '+1',
    engName: 'Dominican Republic',
  ),
  'EC': _CountryCode(
    name: 'Ecuador',
    code: 'EC',
    dialCode: '+593',
    engName: 'Ecuador',
  ),
  'EG': _CountryCode(
    name: 'مصر‎',
    code: 'EG',
    dialCode: '+20',
    engName: 'Egypt',
  ),
  'SV': _CountryCode(
    name: 'El Salvador',
    code: 'SV',
    dialCode: '+503',
    engName: 'El Salvador',
  ),
  'GQ': _CountryCode(
    name: 'Guinea Ecuatorial',
    code: 'GQ',
    dialCode: '+240',
    engName: 'Equatorial Guinea',
  ),
  'ER': _CountryCode(
    name: 'ኤርትራ',
    code: 'ER',
    dialCode: '+291',
    engName: 'Eritrea',
  ),
  'EE': _CountryCode(
    name: 'Eesti',
    code: 'EE',
    dialCode: '+372',
    engName: 'Estonia',
  ),
  'ET': _CountryCode(
    name: 'ኢትዮጵያ',
    code: 'ET',
    dialCode: '+251',
    engName: 'Ethiopia',
  ),
  'FK': _CountryCode(
    name: 'Falkland Islands',
    code: 'FK',
    dialCode: '+500',
    engName: 'Falkland Islands',
  ),
  'FO': _CountryCode(
    name: 'Føroyar',
    code: 'FO',
    dialCode: '+298',
    engName: 'Faroe Islands',
  ),
  'FJ': _CountryCode(
    name: 'Fiji',
    code: 'FJ',
    dialCode: '+679',
    engName: 'Fiji',
  ),
  'FI': _CountryCode(
    name: 'Suomi',
    code: 'FI',
    dialCode: '+358',
    engName: 'Finland',
  ),
  'FR': _CountryCode(
    name: 'France',
    code: 'FR',
    dialCode: '+33',
    engName: 'France',
  ),
  'GF': _CountryCode(
    name: 'Guyane française',
    code: 'GF',
    dialCode: '+594',
    engName: 'French Guiana',
  ),
  'PF': _CountryCode(
    name: 'Polynésie française',
    code: 'PF',
    dialCode: '+689',
    engName: 'French Polynesia',
  ),
  'TF': _CountryCode(
    name: 'Territoire des Terres australes et antarctiques fr',
    code: 'TF',
    dialCode: '+262',
    engName: 'French Southern Territories',
  ),
  'GA': _CountryCode(
    name: 'Gabon',
    code: 'GA',
    dialCode: '+241',
    engName: 'Gabon',
  ),
  'GM': _CountryCode(
    name: 'Gambia',
    code: 'GM',
    dialCode: '+220',
    engName: 'Gambia',
  ),
  'GE': _CountryCode(
    name: 'საქართველო',
    code: 'GE',
    dialCode: '+995',
    engName: 'Georgia',
  ),
  'DE': _CountryCode(
    name: 'Deutschland',
    code: 'DE',
    dialCode: '+49',
    engName: 'Germany',
  ),
  'GH': _CountryCode(
    name: 'Ghana',
    code: 'GH',
    dialCode: '+233',
    engName: 'Ghana',
  ),
  'GI': _CountryCode(
    name: 'Gibraltar',
    code: 'GI',
    dialCode: '+350',
    engName: 'Gibraltar',
  ),
  'GR': _CountryCode(
    name: 'Ελλάδα',
    code: 'GR',
    dialCode: '+30',
    engName: 'Greece',
  ),
  'GL': _CountryCode(
    name: 'Kalaallit Nunaat',
    code: 'GL',
    dialCode: '+299',
    engName: 'Greenland',
  ),
  'GD': _CountryCode(
    name: 'Grenada',
    code: 'GD',
    dialCode: '+1473',
    engName: 'Grenada',
  ),
  'GP': _CountryCode(
    name: 'Guadeloupe',
    code: 'GP',
    dialCode: '+590',
    engName: 'Guadeloupe',
  ),
  'GU': _CountryCode(
    name: 'Guam',
    code: 'GU',
    dialCode: '+1671',
    engName: 'Guam',
  ),
  'GT': _CountryCode(
    name: 'Guatemala',
    code: 'GT',
    dialCode: '+502',
    engName: 'Guatemala',
  ),
  'GG': _CountryCode(
    name: 'Guernsey',
    code: 'GG',
    dialCode: '+44',
    engName: 'Guernsey',
  ),
  'GN': _CountryCode(
    name: 'Guinée',
    code: 'GN',
    dialCode: '+224',
    engName: 'Guinea',
  ),
  'GW': _CountryCode(
    name: 'Guiné-Bissau',
    code: 'GW',
    dialCode: '+245',
    engName: 'Guinea-Bissau',
  ),
  'GY': _CountryCode(
    name: 'Guyana',
    code: 'GY',
    dialCode: '+592',
    engName: 'Guyana',
  ),
  'HT': _CountryCode(
    name: 'Haïti',
    code: 'HT',
    dialCode: '+509',
    engName: 'Haiti',
  ),
  'HM': _CountryCode(
    name: 'Heard Island and McDonald Islands',
    code: 'HM',
    dialCode: '+0',
    engName: 'Heard Island and McDonald Islands',
  ),
  'VA': _CountryCode(
    name: 'Vaticano',
    code: 'VA',
    dialCode: '+379',
    engName: 'Holy See (Vatican City State)',
  ),
  'HN': _CountryCode(
    name: 'Honduras',
    code: 'HN',
    dialCode: '+504',
    engName: 'Honduras',
  ),
  'HK': _CountryCode(
    name: '香港',
    code: 'HK',
    dialCode: '+852',
    engName: 'Hong Kong',
  ),
  'HU': _CountryCode(
    name: 'Magyarország',
    code: 'HU',
    dialCode: '+36',
    engName: 'Hungary',
  ),
  'IS': _CountryCode(
    name: 'Ísland',
    code: 'IS',
    dialCode: '+354',
    engName: 'Iceland',
  ),
  'IN': _CountryCode(
    name: 'भारत',
    code: 'IN',
    dialCode: '+91',
    engName: 'India',
  ),
  'ID': _CountryCode(
    name: 'Indonesia',
    code: 'ID',
    dialCode: '+62',
    engName: 'Indonesia',
  ),
  'IR': _CountryCode(
    name: 'ایران',
    code: 'IR',
    dialCode: '+98',
    engName: 'Iran, Islamic Republic of',
  ),
  'IQ': _CountryCode(
    name: 'العراق',
    code: 'IQ',
    dialCode: '+964',
    engName: 'Iraq',
  ),
  'IE': _CountryCode(
    name: 'Éire',
    code: 'IE',
    dialCode: '+353',
    engName: 'Ireland',
  ),
  'IM': _CountryCode(
    name: 'Isle of Man',
    code: 'IM',
    dialCode: '+44',
    engName: 'Isle of Man',
  ),
  'IL': _CountryCode(
    name: 'ישראל',
    code: 'IL',
    dialCode: '+972',
    engName: 'Israel',
  ),
  'IT': _CountryCode(
    name: 'Italia',
    code: 'IT',
    dialCode: '+39',
    engName: 'Italy',
  ),
  'JM': _CountryCode(
    name: 'Jamaica',
    code: 'JM',
    dialCode: '+1876',
    engName: 'Jamaica',
  ),
  'JP': _CountryCode(
    name: '日本',
    code: 'JP',
    dialCode: '+81',
    engName: 'Japan',
  ),
  'JE': _CountryCode(
    name: 'Jersey',
    code: 'JE',
    dialCode: '+44',
    engName: 'Jersey',
  ),
  'JO': _CountryCode(
    name: 'الأردن',
    code: 'JO',
    dialCode: '+962',
    engName: 'Jordan',
  ),
  'KZ': _CountryCode(
    name: 'Қазақстан',
    code: 'KZ',
    dialCode: '+7',
    engName: 'Kazakhstan',
  ),
  'KE': _CountryCode(
    name: 'Kenya',
    code: 'KE',
    dialCode: '+254',
    engName: 'Kenya',
  ),
  'KI': _CountryCode(
    name: 'Kiribati',
    code: 'KI',
    dialCode: '+686',
    engName: 'Kiribati',
  ),
  'KP': _CountryCode(
    name: '북한',
    code: 'KP',
    dialCode: '+850',
    engName: "Democratic People's Republic of Korea",
  ),
  'KR': _CountryCode(
    name: '대한민국',
    code: 'KR',
    dialCode: '+82',
    engName: 'Republic of Korea',
  ),
  'XK': _CountryCode(
    name: 'Republika e Kosovës',
    code: 'XK',
    dialCode: '+383',
    engName: 'Kosovo',
  ),
  'KW': _CountryCode(
    name: 'الكويت',
    code: 'KW',
    dialCode: '+965',
    engName: 'Kuwait',
  ),
  'KG': _CountryCode(
    name: 'Кыргызстан',
    code: 'KG',
    dialCode: '+996',
    engName: 'Kyrgyzstan',
  ),
  'LA': _CountryCode(
    name: 'ສປປລາວ',
    code: 'LA',
    dialCode: '+856',
    engName: 'Lao People\'s Democratic Republic',
  ),
  'LV': _CountryCode(
    name: 'Latvija',
    code: 'LV',
    dialCode: '+371',
    engName: 'Latvia',
  ),
  'LB': _CountryCode(
    name: 'لبنان',
    code: 'LB',
    dialCode: '+961',
    engName: 'Lebanon',
  ),
  'LS': _CountryCode(
    name: 'Lesotho',
    code: 'LS',
    dialCode: '+266',
    engName: 'Lesotho',
  ),
  'LR': _CountryCode(
    name: 'Liberia',
    code: 'LR',
    dialCode: '+231',
    engName: 'Liberia',
  ),
  'LY': _CountryCode(
    name: '‏ليبيا',
    code: 'LY',
    dialCode: '+218',
    engName: 'Libya',
  ),
  'LI': _CountryCode(
    name: 'Liechtenstein',
    code: 'LI',
    dialCode: '+423',
    engName: 'Liechtenstein',
  ),
  'LT': _CountryCode(
    name: 'Lietuva',
    code: 'LT',
    dialCode: '+370',
    engName: 'Lithuania',
  ),
  'LU': _CountryCode(
    name: 'Luxembourg',
    code: 'LU',
    dialCode: '+352',
    engName: 'Luxembourg',
  ),
  'MO': _CountryCode(
    name: '澳門',
    code: 'MO',
    dialCode: '+853',
    engName: 'Macao',
  ),
  'MK': _CountryCode(
    name: 'Македонија',
    code: 'MK',
    dialCode: '+389',
    engName: 'Macedonia',
  ),
  'MG': _CountryCode(
    name: 'Madagasikara',
    code: 'MG',
    dialCode: '+261',
    engName: 'Madagascar',
  ),
  'MW': _CountryCode(
    name: 'Malawi',
    code: 'MW',
    dialCode: '+265',
    engName: 'Malawi',
  ),
  'MY': _CountryCode(
    name: 'Malaysia',
    code: 'MY',
    dialCode: '+60',
    engName: 'Malaysia',
  ),
  'MV': _CountryCode(
    name: 'Maldives',
    code: 'MV',
    dialCode: '+960',
    engName: 'Maldives',
  ),
  'ML': _CountryCode(
    name: 'Mali',
    code: 'ML',
    dialCode: '+223',
    engName: 'Mali',
  ),
  'MT': _CountryCode(
    name: 'Malta',
    code: 'MT',
    dialCode: '+356',
    engName: 'Malta',
  ),
  'MH': _CountryCode(
    name: 'M̧ajeļ',
    code: 'MH',
    dialCode: '+692',
    engName: 'Marshall Islands',
  ),
  'MQ': _CountryCode(
    name: 'Martinique',
    code: 'MQ',
    dialCode: '+596',
    engName: 'Martinique',
  ),
  'MR': _CountryCode(
    name: 'موريتانيا',
    code: 'MR',
    dialCode: '+222',
    engName: 'Mauritania',
  ),
  'MU': _CountryCode(
    name: 'Maurice',
    code: 'MU',
    dialCode: '+230',
    engName: 'Mauritius',
  ),
  'YT': _CountryCode(
    name: 'Mayotte',
    code: 'YT',
    dialCode: '+262',
    engName: 'Mayotte',
  ),
  'MX': _CountryCode(
    name: 'México',
    code: 'MX',
    dialCode: '+52',
    engName: 'Mexico',
  ),
  'FM': _CountryCode(
    name: 'Micronesia',
    code: 'FM',
    dialCode: '+691',
    engName: 'Micronesia',
  ),
  'MD': _CountryCode(
    name: 'Moldova',
    code: 'MD',
    dialCode: '+373',
    engName: 'Moldova',
  ),
  'MC': _CountryCode(
    name: 'Monaco',
    code: 'MC',
    dialCode: '+377',
    engName: 'Monaco',
  ),
  'MN': _CountryCode(
    name: 'Монгол улс',
    code: 'MN',
    dialCode: '+976',
    engName: 'Mongolia',
  ),
  'ME': _CountryCode(
    name: 'Црна Гора',
    code: 'ME',
    dialCode: '+382',
    engName: 'Montenegro',
  ),
  'MS': _CountryCode(
    name: 'Montserrat',
    code: 'MS',
    dialCode: '+1664',
    engName: 'Montserrat',
  ),
  'MA': _CountryCode(
    name: 'المغرب',
    code: 'MA',
    dialCode: '+212',
    engName: 'Morocco',
  ),
  'MZ': _CountryCode(
    name: 'Moçambique',
    code: 'MZ',
    dialCode: '+258',
    engName: 'Mozambique',
  ),
  'MM': _CountryCode(
    name: 'Myanmar',
    code: 'MM',
    dialCode: '+95',
    engName: 'Myanmar',
  ),
  'NA': _CountryCode(
    name: 'Namibia',
    code: 'NA',
    dialCode: '+264',
    engName: 'Namibia',
  ),
  'NR': _CountryCode(
    name: 'Nauru',
    code: 'NR',
    dialCode: '+674',
    engName: 'Nauru',
  ),
  'NP': _CountryCode(
    name: 'नेपाल',
    code: 'NP',
    dialCode: '+977',
    engName: 'Nepal',
  ),
  'NL': _CountryCode(
    name: 'Nederland',
    code: 'NL',
    dialCode: '+31',
    engName: 'Netherlands',
  ),
  'AN': _CountryCode(
    name: 'Netherlands Antilles',
    code: 'AN',
    dialCode: '+599',
    engName: 'Netherlands Antilles',
  ),
  'NC': _CountryCode(
    name: 'Nouvelle-Calédonie',
    code: 'NC',
    dialCode: '+687',
    engName: 'New Caledonia',
  ),
  'NZ': _CountryCode(
    name: 'New Zealand',
    code: 'NZ',
    dialCode: '+64',
    engName: 'New Zealand',
  ),
  'NI': _CountryCode(
    name: 'Nicaragua',
    code: 'NI',
    dialCode: '+505',
    engName: 'Nicaragua',
  ),
  'NE': _CountryCode(
    name: 'Niger',
    code: 'NE',
    dialCode: '+227',
    engName: 'Niger',
  ),
  'NG': _CountryCode(
    name: 'Nigeria',
    code: 'NG',
    dialCode: '+234',
    engName: 'Nigeria',
  ),
  'NU': _CountryCode(
    name: 'Niuē',
    code: 'NU',
    dialCode: '+683',
    engName: 'Niue',
  ),
  'NF': _CountryCode(
    name: 'Norfolk Island',
    code: 'NF',
    dialCode: '+672',
    engName: 'Norfolk Island',
  ),
  'MP': _CountryCode(
    name: 'Northern Mariana Islands',
    code: 'MP',
    dialCode: '+1670',
    engName: 'Northern Mariana Islands',
  ),
  'NO': _CountryCode(
    name: 'Norge',
    code: 'NO',
    dialCode: '+47',
    engName: 'Norway',
  ),
  'OM': _CountryCode(
    name: 'عمان',
    code: 'OM',
    dialCode: '+968',
    engName: 'Oman',
  ),
  'PK': _CountryCode(
    name: 'Pakistan',
    code: 'PK',
    dialCode: '+92',
    engName: 'Pakistan',
  ),
  'PW': _CountryCode(
    name: 'Palau',
    code: 'PW',
    dialCode: '+680',
    engName: 'Palau',
  ),
  'PS': _CountryCode(
    name: 'فلسطين',
    code: 'PS',
    dialCode: '+970',
    engName: 'Palestine',
  ),
  'PA': _CountryCode(
    name: 'Panamá',
    code: 'PA',
    dialCode: '+507',
    engName: 'Panama',
  ),
  'PG': _CountryCode(
    name: 'Papua Niugini',
    code: 'PG',
    dialCode: '+675',
    engName: 'Papua New Guinea',
  ),
  'PY': _CountryCode(
    name: 'Paraguay',
    code: 'PY',
    dialCode: '+595',
    engName: 'Paraguay',
  ),
  'PE': _CountryCode(
    name: 'Perú',
    code: 'PE',
    dialCode: '+51',
    engName: 'Peru',
  ),
  'PH': _CountryCode(
    name: 'Pilipinas',
    code: 'PH',
    dialCode: '+63',
    engName: 'Philippines',
  ),
  'PN': _CountryCode(
    name: 'Pitcairn Islands',
    code: 'PN',
    dialCode: '+64',
    engName: 'Pitcairn Islands',
  ),
  'PL': _CountryCode(
    name: 'Polska',
    code: 'PL',
    dialCode: '+48',
    engName: 'Poland',
  ),
  'RT': _CountryCode(
    name: 'Portugal',
    code: 'PT',
    dialCode: '+351',
    engName: 'Portugal',
  ),
  // _CountryCode(
  //   name: 'Puerto Rico',
  //   code: 'PR',
  //   dialCode: '+1939',
  // ),
  'PR': _CountryCode(
    name: 'Puerto Rico',
    code: 'PR',
    dialCode: '+1787',
    engName: 'Puerto Rico',
  ),
  'QA': _CountryCode(
    name: 'قطر',
    code: 'QA',
    dialCode: '+974',
    engName: 'Qatar',
  ),
  'RO': _CountryCode(
    name: 'România',
    code: 'RO',
    dialCode: '+40',
    engName: 'Romania',
  ),
  'RU': _CountryCode(
    name: 'Россия',
    code: 'RU',
    dialCode: '+7',
    engName: 'Russia',
  ),
  'RW': _CountryCode(
    name: 'Rwanda',
    code: 'RW',
    dialCode: '+250',
    engName: 'Rwanda',
  ),
  'RE': _CountryCode(
    name: 'La Réunion',
    code: 'RE',
    dialCode: '+262',
    engName: 'Réunion',
  ),
  'BL': _CountryCode(
    name: 'Saint-Barthélemy',
    code: 'BL',
    dialCode: '+590',
    engName: 'Saint Barthélemy',
  ),
  'SH': _CountryCode(
    name: 'Saint Helena',
    code: 'SH',
    dialCode: '+290',
    engName: 'Saint Helena',
  ),
  'KN': _CountryCode(
    name: 'Saint Kitts and Nevis',
    code: 'KN',
    dialCode: '+1869',
    engName: 'Saint Kitts and Nevis',
  ),
  'LC': _CountryCode(
    name: 'Saint Lucia',
    code: 'LC',
    dialCode: '+1758',
    engName: 'Saint Lucia',
  ),
  'MF': _CountryCode(
    name: 'Saint-Martin',
    code: 'MF',
    dialCode: '+590',
    engName: 'Saint Martin',
  ),
  'PM': _CountryCode(
    name: 'Saint-Pierre-et-Miquelon',
    code: 'PM',
    dialCode: '+508',
    engName: 'Saint Pierre and Miquelon',
  ),
  'VC': _CountryCode(
    name: 'Saint Vincent and the Grenadines',
    code: 'VC',
    dialCode: '+1784',
    engName: 'Saint Vincent and the Grenadines',
  ),
  'WS': _CountryCode(
    name: 'Samoa',
    code: 'WS',
    dialCode: '+685',
    engName: 'Samoa',
  ),
  'SM': _CountryCode(
    name: 'San Marino',
    code: 'SM',
    dialCode: '+378',
    engName: 'San Marino',
  ),
  'ST': _CountryCode(
    name: 'São Tomé e Príncipe',
    code: 'ST',
    dialCode: '+239',
    engName: 'São Tomé and Príncipe',
  ),
  'SA': _CountryCode(
    name: 'العربية السعودية',
    code: 'SA',
    dialCode: '+966',
    engName: 'Saudi Arabia',
  ),
  'SN': _CountryCode(
    name: 'Sénégal',
    code: 'SN',
    dialCode: '+221',
    engName: 'Senegal',
  ),
  'RS': _CountryCode(
    name: 'Србија',
    code: 'RS',
    dialCode: '+381',
    engName: 'Serbia',
  ),
  'SC': _CountryCode(
    name: 'Seychelles',
    code: 'SC',
    dialCode: '+248',
    engName: 'Seychelles',
  ),
  'SL': _CountryCode(
    name: 'Sierra Leone',
    code: 'SL',
    dialCode: '+232',
    engName: 'Sierra Leone',
  ),
  'SG': _CountryCode(
    name: 'Singapore',
    code: 'SG',
    dialCode: '+65',
    engName: 'Singapore',
  ),
  'SK': _CountryCode(
    name: 'Slovensko',
    code: 'SK',
    dialCode: '+421',
    engName: 'Slovakia',
  ),
  'SI': _CountryCode(
    name: 'Slovenija',
    code: 'SI',
    dialCode: '+386',
    engName: 'Slovenia',
  ),
  'SB': _CountryCode(
    name: 'Solomon Islands',
    code: 'SB',
    dialCode: '+677',
    engName: 'Solomon Islands',
  ),
  'SO': _CountryCode(
    name: 'Soomaaliya',
    code: 'SO',
    dialCode: '+252',
    engName: 'Somalia',
  ),
  'ZA': _CountryCode(
    name: 'South Africa',
    code: 'ZA',
    dialCode: '+27',
    engName: 'South Africa',
  ),
  'SS': _CountryCode(
    name: 'South Sudan',
    code: 'SS',
    dialCode: '+211',
    engName: 'South Sudan',
  ),
  'GS': _CountryCode(
    name: 'South Georgia',
    code: 'GS',
    dialCode: '+500',
    engName: 'South Georgia and the South Sandwich Islands',
  ),
  'ES': _CountryCode(
    name: 'España',
    code: 'ES',
    dialCode: '+34',
    engName: 'Spain',
  ),
  'LK': _CountryCode(
    name: 'Sri Lanka',
    code: 'LK',
    dialCode: '+94',
    engName: 'Sri Lanka',
  ),
  'SD': _CountryCode(
    name: 'السودان',
    code: 'SD',
    dialCode: '+249',
    engName: 'Sudan',
  ),
  'SR': _CountryCode(
    name: 'Suriname',
    code: 'SR',
    dialCode: '+597',
    engName: 'Suriname',
  ),
  'SJ': _CountryCode(
    name: 'Svalbard og Jan Mayen',
    code: 'SJ',
    dialCode: '+47',
    engName: 'Svalbard and Jan Mayen',
  ),
  'SZ': _CountryCode(
    name: 'Swaziland',
    code: 'SZ',
    dialCode: '+268',
    engName: 'Swaziland',
  ),
  'SE': _CountryCode(
    name: 'Sverige',
    code: 'SE',
    dialCode: '+46',
    engName: 'Sweden',
  ),
  'CH': _CountryCode(
    name: 'Schweiz',
    code: 'CH',
    dialCode: '+41',
    engName: 'Switzerland',
  ),
  'SY': _CountryCode(
    name: 'سوريا',
    code: 'SY',
    dialCode: '+963',
    engName: 'Syria',
  ),
  'TW': _CountryCode(
    name: '臺灣',
    code: 'TW',
    dialCode: '+886',
    engName: 'Taiwan',
  ),
  'TJ': _CountryCode(
    name: 'Тоҷикистон',
    code: 'TJ',
    dialCode: '+992',
    engName: 'Tajikistan',
  ),
  'TZ': _CountryCode(
    name: 'Tanzania',
    code: 'TZ',
    dialCode: '+255',
    engName: 'Tanzania',
  ),
  'TH': _CountryCode(
    name: 'ประเทศไทย',
    code: 'TH',
    dialCode: '+66',
    engName: 'Thailand',
  ),
  'TL': _CountryCode(
    name: 'Timor-Leste',
    code: 'TL',
    dialCode: '+670',
    engName: 'Timor-Leste',
  ),
  'TG': _CountryCode(
    name: 'Togo',
    code: 'TG',
    dialCode: '+228',
    engName: 'Togo',
  ),
  'TK': _CountryCode(
    name: 'Tokelau',
    code: 'TK',
    dialCode: '+690',
    engName: 'Tokelau',
  ),
  'TO': _CountryCode(
    name: 'Tonga',
    code: 'TO',
    dialCode: '+676',
    engName: 'Tonga',
  ),
  'TT': _CountryCode(
    name: 'Trinidad and Tobago',
    code: 'TT',
    dialCode: '+1868',
    engName: 'Trinidad and Tobago',
  ),
  'TN': _CountryCode(
    name: 'تونس',
    code: 'TN',
    dialCode: '+216',
    engName: 'Tunisia',
  ),
  'TR': _CountryCode(
    name: 'Türkiye',
    code: 'TR',
    dialCode: '+90',
    engName: 'Turkey',
  ),
  'TM': _CountryCode(
    name: 'Türkmenistan',
    code: 'TM',
    dialCode: '+993',
    engName: 'Turkmenistan',
  ),
  'TC': _CountryCode(
    name: 'Turks and Caicos Islands',
    code: 'TC',
    dialCode: '+1649',
    engName: 'Turks and Caicos Islands',
  ),
  'TV': _CountryCode(
    name: 'Tuvalu',
    code: 'TV',
    dialCode: '+688',
    engName: 'Tuvalu',
  ),
  'UG': _CountryCode(
    name: 'Uganda',
    code: 'UG',
    dialCode: '+256',
    engName: 'Uganda',
  ),
  'UA': _CountryCode(
    name: 'Україна',
    code: 'UA',
    dialCode: '+380',
    engName: 'Ukraine',
  ),
  'AE': _CountryCode(
    name: 'دولة الإمارات العربية المتحدة',
    code: 'AE',
    dialCode: '+971',
    engName: 'United Arab Emirates',
  ),
  'GB': _CountryCode(
    name: 'United Kingdom',
    code: 'GB',
    dialCode: '+44',
    engName: 'United Kingdom',
  ),
  'US': _CountryCode(
    name: 'United States',
    code: 'US',
    dialCode: '+1',
    engName: 'United States',
  ),
  'UY': _CountryCode(
    name: 'Uruguay',
    code: 'UY',
    dialCode: '+598',
    engName: 'Uruguay',
  ),
  'UZ': _CountryCode(
    name: 'O‘zbekiston',
    code: 'UZ',
    dialCode: '+998',
    engName: 'Uzbekistan',
  ),
  'VU': _CountryCode(
    name: 'Vanuatu',
    code: 'VU',
    dialCode: '+678',
    engName: 'Vanuatu',
  ),
  'VE': _CountryCode(
    name: 'Venezuela',
    code: 'VE',
    dialCode: '+58',
    engName: 'Venezuela',
  ),
  'VN': _CountryCode(
    name: 'Việt Nam',
    code: 'VN',
    dialCode: '+84',
    engName: 'Vietnam',
  ),
  'VG': _CountryCode(
    name: 'British Virgin Islands',
    code: 'VG',
    dialCode: '+1284',
    engName: 'British Virgin Islands',
  ),
  'VI': _CountryCode(
    name: 'United States Virgin Islands',
    code: 'VI',
    dialCode: '+1340',
    engName: 'United States Virgin Islands',
  ),
  'WF': _CountryCode(
    name: 'Wallis et Futuna',
    code: 'WF',
    dialCode: '+681',
    engName: 'Wallis et Futuna',
  ),
  'YE': _CountryCode(
    name: 'اليَمَن',
    code: 'YE',
    dialCode: '+967',
    engName: 'Yemen',
  ),
  'ZM': _CountryCode(
    name: 'Zambia',
    code: 'ZM',
    dialCode: '+260',
    engName: 'Zambia',
  ),
  'ZW': _CountryCode(
    name: 'Zimbabwe',
    code: 'ZW',
    dialCode: '+263',
    engName: 'Zimbabwe',
  ),
};

String countryCodeToEngName(String countryCode) {
  if (countryCodeMap.containsKey(countryCode)) {
    return countryCodeMap[countryCode]!.engName;
  }
  return 'Undefined';
}
