import 'certificate_service.dart';

final dummyDatabaseCertificates = [
  DatabaseCertificate(
    null,
    certID: 'cert-id-1',
    personID: 'person-id-1',
    name: 'name-1',
    brand: 'brand-1',
    numDose: 1,
    issueTime: 'issue-time-1',
    issuer: 'issuer-1',
    remark: 'remark-1',
    globalChainTxHash: 'global-chain-tx-hash-1',
    globalChainBlockNum: 1,
    globalChainTimeStamp: 'global-chain-time-stamp-1',
    localChainID: 'local-chain-id-1',
    localChainTxHash: 'local-chain-tx-hash-1',
    localChainBlockNum: 1,
    localChainTimeStamp: 'local-chain-time-stamp-1',
    isValidated: false,
  ),
  DatabaseCertificate(
    null,
    certID: 'cert-id-2',
    personID: 'person-id-2',
    name: 'name-2',
    brand: 'brand-2',
    numDose: 2,
    issueTime: 'issue-time-2',
    issuer: 'issuer-2',
    remark: 'remark-2',
    globalChainTxHash: 'global-chain-tx-hash-2',
    globalChainBlockNum: 2,
    globalChainTimeStamp: 'global-chain-time-stamp-2',
    localChainID: 'local-chain-id-2',
    localChainTxHash: 'local-chain-tx-hash-2',
    localChainBlockNum: 2,
    localChainTimeStamp: 'local-chain-time-stamp-2',
    isValidated: true,
  ),
  DatabaseCertificate(
    null,
    certID: 'cert-id-3',
    personID: 'person-id-3',
    name: 'name-3',
    brand: 'brand-3',
    numDose: 3,
    issueTime: 'issue-time-3',
    issuer: 'issuer-3',
    remark: 'remark-3',
    globalChainTxHash: 'global-chain-tx-hash-3',
    globalChainBlockNum: 3,
    globalChainTimeStamp: 'global-chain-time-stamp-3',
    localChainID: 'local-chain-id-3',
    localChainTxHash: 'local-chain-tx-hash-3',
    localChainBlockNum: 3,
    localChainTimeStamp: 'local-chain-time-stamp-3',
    isValidated: true,
  ),
];
